title: ProudCity
description: >- # this means to ignore newlines until "baseurl:"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  pages:
    output: true
    permalink: :title